spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com # SMTP 서버 호스트
    port: 465 # SMTP 서버 포트
    username: ${SMTP_MAIL_USERNAME} # SMTP 서버 로그인 아이디 (발신자)
    password: ${SMTP_MAIL_PASSWORD} # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          ssl:
            enable: true
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

mail:
  address:
    admin: admin@gmail.com

multipart:
  max-file-size: 10MB
  max-request-size: 10MB
  location: /Users/gimjaehui/profileImages
  enabled: true
  upload:
    path: /Users/gimjaehui/profileImages

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420